<?php

/**
 * @file
 * Contains openid_connect_harid.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function openid_connect_harid_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the openid_connect_harid module.
    case 'help.page.openid_connect_harid':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OpenID Connect HarID Client') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_openid_connect_post_authorize().
 */
function openid_connect_harid_openid_connect_post_authorize(UserInterface $account, array $context) {
  if ($context['plugin_id'] === 'harid') {
    if (isset($context['userinfo']['ui_locales'])) {
      // TODO See if there should be a check for allowed values. Example: en, et, ru
      $account->set('langcode', $context['userinfo']['ui_locales']);
      $account->set('preferred_langcode', $context['userinfo']['ui_locales']);
      $account->save();
    }
  }
}

/**
 * Imlements hook_openid_connect_pre_authorize().
 */
function openid_connect_harid_openid_connect_pre_authorize($account, array $context) {
  if ($context['plugin_id'] === 'harid') {
    $settings = \Drupal::configFactory()->get('openid_connect.settings.harid')->get('settings');

    // TODO See if we should also check the presence of personal_code
    if ($settings['require_strong_session'] === TRUE && $context['userinfo']['strong_session'] !== TRUE) {
      \Drupal::messenger()
        ->addError(t('A strong session is required! Please use ID-card or Moble-ID to authenticate with HarID.'));
      return FALSE;
    }
  }

  return TRUE;
}
